//// ------------------------------------------------------------------------------
////  <auto-generated>
////      This code was generated by coded UI test builder.
////      Version: 15.0.0.0
////
////      Changes to this file may cause incorrect behavior and will be lost if
////      the code is regenerated.
////  </auto-generated>
//// ------------------------------------------------------------------------------

//namespace BehaviorTests
//{
//    using System;
//    using System.CodeDom.Compiler;
//    using System.Collections.Generic;
//    using System.Drawing;
//    using System.Text.RegularExpressions;
//    using System.Windows.Input;
//    using Microsoft.VisualStudio.TestTools.UITest.Extension;
//    using Microsoft.VisualStudio.TestTools.UITesting;
//    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
//    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
//    using Microsoft.VisualStudio.TestTools.UnitTesting;
//    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
//    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
//    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public partial class UIMap
//    {
        
//        /// <summary>
//        /// LoginTest - Use 'LoginTestParams' to pass parameters into this method.
//        /// </summary>
//        public void LoginTest()
//        {
//            #region Variable Declarations
//            WpfEdit uITxtUsernameEdit = this.UICapstoneEmployeeScheWindow.UITxtUsernameEdit;
//            WpfText uIPASSWORDText = this.UICapstoneEmployeeScheWindow.UIPASSWORDText;
//            WpfEdit uITxtPasswordEdit = this.UICapstoneEmployeeScheWindow.UITxtPasswordEdit;
//            WpfButton uISUBMITButton = this.UICapstoneEmployeeScheWindow.UISUBMITButton;
//            #endregion

//            // Launch '%USERPROFILE%\Desktop\CapstoneEmployeeScheduler.exe'
//            ApplicationUnderTest uICapstoneEmployeeScheWindow = ApplicationUnderTest.Launch(this.LoginTestParams.UICapstoneEmployeeScheWindowExePath, this.LoginTestParams.UICapstoneEmployeeScheWindowAlternateExePath);

//            // Type 'admin' in 'txtUsername' text box
//            uITxtUsernameEdit.Text = this.LoginTestParams.UITxtUsernameEditText;

//            // Click 'PASSWORD' label
//            Mouse.Click(uIPASSWORDText, new Point(45, 4));

//            // Type '********' in 'txtPassword' text box
//            Keyboard.SendKeys(uITxtPasswordEdit, this.LoginTestParams.UITxtPasswordEditSendKeys, true);

//            // Click 'SUBMIT' button
//            Mouse.Click(uISUBMITButton, new Point(42, 20));
//        }
        
//        /// <summary>
//        /// NavigatingPages - Use 'NavigatingPagesParams' to pass parameters into this method.
//        /// </summary>
//        public void NavigatingPages()
//        {
//            #region Variable Declarations
//            WpfText uIUSERNAMEText = this.UICapstoneEmployeeScheWindow.UIUSERNAMEText;
//            WpfEdit uITxtUsernameEdit = this.UICapstoneEmployeeScheWindow.UITxtUsernameEdit;
//            WpfEdit uITxtPasswordEdit = this.UICapstoneEmployeeScheWindow.UITxtPasswordEdit;
//            WpfButton uISUBMITButton = this.UICapstoneEmployeeScheWindow.UISUBMITButton;
//            WpfButton uIGenerateScheduleButton = this.UICapstoneEmployeeScheWindow1.UIMainPane.UIGenerateScheduleButton;
//            WinButton uIOKButton = this.UIGenerateScheduleWindow.UIOKWindow.UIOKButton;
//            WpfButton uIHISTORYButton = this.UICapstoneEmployeeScheWindow1.UIHISTORYButton;
//            WpfButton uIHOMEButton = this.UICapstoneEmployeeScheWindow1.UIHOMEButton;
//            WpfButton uIEMPLOYEESButton = this.UICapstoneEmployeeScheWindow1.UIEMPLOYEESButton;
//            WpfButton uIROLESButton = this.UICapstoneEmployeeScheWindow1.UIROLESButton;
//            #endregion

//            // Launch '%USERPROFILE%\Desktop\CapstoneEmployeeScheduler.exe'
//            ApplicationUnderTest uICapstoneEmployeeScheWindow = ApplicationUnderTest.Launch(this.NavigatingPagesParams.UICapstoneEmployeeScheWindowExePath, this.NavigatingPagesParams.UICapstoneEmployeeScheWindowAlternateExePath);

//            // Click 'USERNAME' label
//            Mouse.Click(uIUSERNAMEText, new Point(73, 8));

//            // Type 'admin' in 'txtUsername' text box
//            uITxtUsernameEdit.Text = this.NavigatingPagesParams.UITxtUsernameEditText;

//            // Click 'txtPassword' text box
//            Mouse.Click(uITxtPasswordEdit, new Point(144, 1));

//            // Click 'txtPassword' text box
//            Mouse.Click(uITxtPasswordEdit, new Point(140, 14));

//            // Type '********' in 'txtPassword' text box
//            Keyboard.SendKeys(uITxtPasswordEdit, this.NavigatingPagesParams.UITxtPasswordEditSendKeys, true);

//            // Click 'SUBMIT' button
//            Mouse.Click(uISUBMITButton, new Point(21, 13));

//            // Click 'Generate Schedule' button
//            Mouse.Click(uIGenerateScheduleButton, new Point(73, 33));

//            // Click 'OK' button
//            Mouse.Click(uIOKButton, new Point(50, 13));

//            // Click 'HISTORY' button
//            Mouse.Click(uIHISTORYButton, new Point(66, 32));

//            // Click 'HOME' button
//            Mouse.Click(uIHOMEButton, new Point(65, 42));

//            // Click 'EMPLOYEES' button
//            Mouse.Click(uIEMPLOYEESButton, new Point(69, 43));

//            // Click 'HOME' button
//            Mouse.Click(uIHOMEButton, new Point(46, 28));

//            // Click 'ROLES' button
//            Mouse.Click(uIROLESButton, new Point(54, 52));

//            // Click 'HOME' button
//            Mouse.Click(uIHOMEButton, new Point(69, 30));
//        }
        
//        #region Properties
//        public virtual LoginTestParams LoginTestParams
//        {
//            get
//            {
//                if ((this.mLoginTestParams == null))
//                {
//                    this.mLoginTestParams = new LoginTestParams();
//                }
//                return this.mLoginTestParams;
//            }
//        }
        
//        public virtual NavigatingPagesParams NavigatingPagesParams
//        {
//            get
//            {
//                if ((this.mNavigatingPagesParams == null))
//                {
//                    this.mNavigatingPagesParams = new NavigatingPagesParams();
//                }
//                return this.mNavigatingPagesParams;
//            }
//        }
        
//        public UIWpfWindow UIWpfWindow
//        {
//            get
//            {
//                if ((this.mUIWpfWindow == null))
//                {
//                    this.mUIWpfWindow = new UIWpfWindow();
//                }
//                return this.mUIWpfWindow;
//            }
//        }
        
//        public UICapstoneEmployeeScheWindow UICapstoneEmployeeScheWindow
//        {
//            get
//            {
//                if ((this.mUICapstoneEmployeeScheWindow == null))
//                {
//                    this.mUICapstoneEmployeeScheWindow = new UICapstoneEmployeeScheWindow();
//                }
//                return this.mUICapstoneEmployeeScheWindow;
//            }
//        }
        
//        public UIOKWindow UIOKWindow
//        {
//            get
//            {
//                if ((this.mUIOKWindow == null))
//                {
//                    this.mUIOKWindow = new UIOKWindow();
//                }
//                return this.mUIOKWindow;
//            }
//        }
        
//        public UIGenerateScheduleWindow UIGenerateScheduleWindow
//        {
//            get
//            {
//                if ((this.mUIGenerateScheduleWindow == null))
//                {
//                    this.mUIGenerateScheduleWindow = new UIGenerateScheduleWindow();
//                }
//                return this.mUIGenerateScheduleWindow;
//            }
//        }
        
//        public UILogoutSuccessfulWindow UILogoutSuccessfulWindow
//        {
//            get
//            {
//                if ((this.mUILogoutSuccessfulWindow == null))
//                {
//                    this.mUILogoutSuccessfulWindow = new UILogoutSuccessfulWindow();
//                }
//                return this.mUILogoutSuccessfulWindow;
//            }
//        }
        
//        public UICapstoneEmployeeScheWindow1 UICapstoneEmployeeScheWindow1
//        {
//            get
//            {
//                if ((this.mUICapstoneEmployeeScheWindow1 == null))
//                {
//                    this.mUICapstoneEmployeeScheWindow1 = new UICapstoneEmployeeScheWindow1();
//                }
//                return this.mUICapstoneEmployeeScheWindow1;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private LoginTestParams mLoginTestParams;
        
//        private NavigatingPagesParams mNavigatingPagesParams;
        
//        private UIWpfWindow mUIWpfWindow;
        
//        private UICapstoneEmployeeScheWindow mUICapstoneEmployeeScheWindow;
        
//        private UIOKWindow mUIOKWindow;
        
//        private UIGenerateScheduleWindow mUIGenerateScheduleWindow;
        
//        private UILogoutSuccessfulWindow mUILogoutSuccessfulWindow;
        
//        private UICapstoneEmployeeScheWindow1 mUICapstoneEmployeeScheWindow1;
//        #endregion
//    }
    
//    /// <summary>
//    /// Parameters to be passed into 'LoginTest'
//    /// </summary>
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class LoginTestParams
//    {
        
//        #region Fields
//        /// <summary>
//        /// Launch '%USERPROFILE%\Desktop\CapstoneEmployeeScheduler.exe'
//        /// </summary>
//        public string UICapstoneEmployeeScheWindowExePath = "C:\\Users\\Da Jew\\Desktop\\CapstoneEmployeeScheduler.exe";
        
//        /// <summary>
//        /// Launch '%USERPROFILE%\Desktop\CapstoneEmployeeScheduler.exe'
//        /// </summary>
//        public string UICapstoneEmployeeScheWindowAlternateExePath = "%USERPROFILE%\\Desktop\\CapstoneEmployeeScheduler.exe";
        
//        /// <summary>
//        /// Type 'admin' in 'txtUsername' text box
//        /// </summary>
//        public string UITxtUsernameEditText = "admin";
        
//        /// <summary>
//        /// Type '********' in 'txtPassword' text box
//        /// </summary>
//        public string UITxtPasswordEditSendKeys = "ltMtR4VOfdZS3D8xaljxesqUwEXKaQEX";
//        #endregion
//    }
    
//    /// <summary>
//    /// Parameters to be passed into 'NavigatingPages'
//    /// </summary>
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class NavigatingPagesParams
//    {
        
//        #region Fields
//        /// <summary>
//        /// Launch '%USERPROFILE%\Desktop\CapstoneEmployeeScheduler.exe'
//        /// </summary>
//        public string UICapstoneEmployeeScheWindowExePath = "C:\\Users\\Da Jew\\Desktop\\CapstoneEmployeeScheduler.exe";
        
//        /// <summary>
//        /// Launch '%USERPROFILE%\Desktop\CapstoneEmployeeScheduler.exe'
//        /// </summary>
//        public string UICapstoneEmployeeScheWindowAlternateExePath = "%USERPROFILE%\\Desktop\\CapstoneEmployeeScheduler.exe";
        
//        /// <summary>
//        /// Type 'admin' in 'txtUsername' text box
//        /// </summary>
//        public string UITxtUsernameEditText = "admin";
        
//        /// <summary>
//        /// Type '********' in 'txtPassword' text box
//        /// </summary>
//        public string UITxtPasswordEditSendKeys = "ltMtR4VOfdZS3D8xaljxesqUwEXKaQEX";
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UIWpfWindow : WpfWindow
//    {
        
//        public UIWpfWindow()
//        {
//            #region Search Criteria
//            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
//            #endregion
//        }
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UICapstoneEmployeeScheWindow : WpfWindow
//    {
        
//        public UICapstoneEmployeeScheWindow()
//        {
//            #region Search Criteria
//            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Capstone Employee Scheduler - Login";
//            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
//            this.WindowTitles.Add("Capstone Employee Scheduler - Login");
//            #endregion
//        }
        
//        #region Properties
//        public WpfEdit UITxtUsernameEdit
//        {
//            get
//            {
//                if ((this.mUITxtUsernameEdit == null))
//                {
//                    this.mUITxtUsernameEdit = new WpfEdit(this);
//                    #region Search Criteria
//                    this.mUITxtUsernameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtUsername";
//                    this.mUITxtUsernameEdit.WindowTitles.Add("Capstone Employee Scheduler - Login");
//                    #endregion
//                }
//                return this.mUITxtUsernameEdit;
//            }
//        }
        
//        public WpfEdit UITxtPasswordEdit
//        {
//            get
//            {
//                if ((this.mUITxtPasswordEdit == null))
//                {
//                    this.mUITxtPasswordEdit = new WpfEdit(this);
//                    #region Search Criteria
//                    this.mUITxtPasswordEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtPassword";
//                    this.mUITxtPasswordEdit.WindowTitles.Add("Capstone Employee Scheduler - Login");
//                    #endregion
//                }
//                return this.mUITxtPasswordEdit;
//            }
//        }
        
//        public WpfText UIPASSWORDText
//        {
//            get
//            {
//                if ((this.mUIPASSWORDText == null))
//                {
//                    this.mUIPASSWORDText = new WpfText(this);
//                    #region Search Criteria
//                    this.mUIPASSWORDText.SearchProperties[WpfText.PropertyNames.AutomationId] = "tbPassword";
//                    this.mUIPASSWORDText.WindowTitles.Add("Capstone Employee Scheduler - Login");
//                    #endregion
//                }
//                return this.mUIPASSWORDText;
//            }
//        }
        
//        public WpfButton UISUBMITButton
//        {
//            get
//            {
//                if ((this.mUISUBMITButton == null))
//                {
//                    this.mUISUBMITButton = new WpfButton(this);
//                    #region Search Criteria
//                    this.mUISUBMITButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "buttonSubmit";
//                    this.mUISUBMITButton.WindowTitles.Add("Capstone Employee Scheduler - Login");
//                    #endregion
//                }
//                return this.mUISUBMITButton;
//            }
//        }
        
//        public WpfText UIUSERNAMEText
//        {
//            get
//            {
//                if ((this.mUIUSERNAMEText == null))
//                {
//                    this.mUIUSERNAMEText = new WpfText(this);
//                    #region Search Criteria
//                    this.mUIUSERNAMEText.SearchProperties[WpfText.PropertyNames.AutomationId] = "tbUsername";
//                    this.mUIUSERNAMEText.WindowTitles.Add("Capstone Employee Scheduler - Login");
//                    #endregion
//                }
//                return this.mUIUSERNAMEText;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private WpfEdit mUITxtUsernameEdit;
        
//        private WpfEdit mUITxtPasswordEdit;
        
//        private WpfText mUIPASSWORDText;
        
//        private WpfButton mUISUBMITButton;
        
//        private WpfText mUIUSERNAMEText;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UIOKWindow : WinWindow
//    {
        
//        public UIOKWindow()
//        {
//            #region Search Criteria
//            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
//            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
//            this.WindowTitles.Add("OK");
//            #endregion
//        }
        
//        #region Properties
//        public WinButton UIOKButton
//        {
//            get
//            {
//                if ((this.mUIOKButton == null))
//                {
//                    this.mUIOKButton = new WinButton(this);
//                    #region Search Criteria
//                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
//                    this.mUIOKButton.WindowTitles.Add("OK");
//                    #endregion
//                }
//                return this.mUIOKButton;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private WinButton mUIOKButton;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UIGenerateScheduleWindow : WinWindow
//    {
        
//        public UIGenerateScheduleWindow()
//        {
//            #region Search Criteria
//            this.SearchProperties[WinWindow.PropertyNames.Name] = "Generate Schedule";
//            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
//            this.WindowTitles.Add("Generate Schedule");
//            #endregion
//        }
        
//        #region Properties
//        public UIOKWindow1 UIOKWindow
//        {
//            get
//            {
//                if ((this.mUIOKWindow == null))
//                {
//                    this.mUIOKWindow = new UIOKWindow1(this);
//                }
//                return this.mUIOKWindow;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private UIOKWindow1 mUIOKWindow;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UIOKWindow1 : WinWindow
//    {
        
//        public UIOKWindow1(UITestControl searchLimitContainer) : 
//                base(searchLimitContainer)
//        {
//            #region Search Criteria
//            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
//            this.WindowTitles.Add("Generate Schedule");
//            #endregion
//        }
        
//        #region Properties
//        public WinButton UIOKButton
//        {
//            get
//            {
//                if ((this.mUIOKButton == null))
//                {
//                    this.mUIOKButton = new WinButton(this);
//                    #region Search Criteria
//                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
//                    this.mUIOKButton.WindowTitles.Add("Generate Schedule");
//                    #endregion
//                }
//                return this.mUIOKButton;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private WinButton mUIOKButton;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UILogoutSuccessfulWindow : WinWindow
//    {
        
//        public UILogoutSuccessfulWindow()
//        {
//            #region Search Criteria
//            this.SearchProperties[WinWindow.PropertyNames.Name] = "Logout Successful";
//            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
//            this.WindowTitles.Add("Logout Successful");
//            #endregion
//        }
        
//        #region Properties
//        public UIOKWindow2 UIOKWindow
//        {
//            get
//            {
//                if ((this.mUIOKWindow == null))
//                {
//                    this.mUIOKWindow = new UIOKWindow2(this);
//                }
//                return this.mUIOKWindow;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private UIOKWindow2 mUIOKWindow;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UIOKWindow2 : WinWindow
//    {
        
//        public UIOKWindow2(UITestControl searchLimitContainer) : 
//                base(searchLimitContainer)
//        {
//            #region Search Criteria
//            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
//            this.WindowTitles.Add("Logout Successful");
//            #endregion
//        }
        
//        #region Properties
//        public WinButton UIOKButton
//        {
//            get
//            {
//                if ((this.mUIOKButton == null))
//                {
//                    this.mUIOKButton = new WinButton(this);
//                    #region Search Criteria
//                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
//                    this.mUIOKButton.WindowTitles.Add("Logout Successful");
//                    #endregion
//                }
//                return this.mUIOKButton;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private WinButton mUIOKButton;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UICapstoneEmployeeScheWindow1 : WpfWindow
//    {
        
//        public UICapstoneEmployeeScheWindow1()
//        {
//            #region Search Criteria
//            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Capstone Employee Scheduler - Home";
//            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
//            this.WindowTitles.Add("Capstone Employee Scheduler - Home");
//            #endregion
//        }
        
//        #region Properties
//        public UIMainPane UIMainPane
//        {
//            get
//            {
//                if ((this.mUIMainPane == null))
//                {
//                    this.mUIMainPane = new UIMainPane(this);
//                }
//                return this.mUIMainPane;
//            }
//        }
        
//        public WpfButton UIHISTORYButton
//        {
//            get
//            {
//                if ((this.mUIHISTORYButton == null))
//                {
//                    this.mUIHISTORYButton = new WpfButton(this);
//                    #region Search Criteria
//                    this.mUIHISTORYButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "History";
//                    this.mUIHISTORYButton.WindowTitles.Add("Capstone Employee Scheduler - Home");
//                    #endregion
//                }
//                return this.mUIHISTORYButton;
//            }
//        }
        
//        public WpfButton UIHOMEButton
//        {
//            get
//            {
//                if ((this.mUIHOMEButton == null))
//                {
//                    this.mUIHOMEButton = new WpfButton(this);
//                    #region Search Criteria
//                    this.mUIHOMEButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "home";
//                    this.mUIHOMEButton.WindowTitles.Add("Capstone Employee Scheduler - Home");
//                    #endregion
//                }
//                return this.mUIHOMEButton;
//            }
//        }
        
//        public WpfButton UIEMPLOYEESButton
//        {
//            get
//            {
//                if ((this.mUIEMPLOYEESButton == null))
//                {
//                    this.mUIEMPLOYEESButton = new WpfButton(this);
//                    #region Search Criteria
//                    this.mUIEMPLOYEESButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Employees";
//                    this.mUIEMPLOYEESButton.WindowTitles.Add("Capstone Employee Scheduler - Home");
//                    #endregion
//                }
//                return this.mUIEMPLOYEESButton;
//            }
//        }
        
//        public WpfButton UIROLESButton
//        {
//            get
//            {
//                if ((this.mUIROLESButton == null))
//                {
//                    this.mUIROLESButton = new WpfButton(this);
//                    #region Search Criteria
//                    this.mUIROLESButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Roles";
//                    this.mUIROLESButton.WindowTitles.Add("Capstone Employee Scheduler - Home");
//                    #endregion
//                }
//                return this.mUIROLESButton;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private UIMainPane mUIMainPane;
        
//        private WpfButton mUIHISTORYButton;
        
//        private WpfButton mUIHOMEButton;
        
//        private WpfButton mUIEMPLOYEESButton;
        
//        private WpfButton mUIROLESButton;
//        #endregion
//    }
    
//    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
//    public class UIMainPane : WpfPane
//    {
        
//        public UIMainPane(UITestControl searchLimitContainer) : 
//                base(searchLimitContainer)
//        {
//            #region Search Criteria
//            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.Frame";
//            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "Main";
//            this.WindowTitles.Add("Capstone Employee Scheduler - Home");
//            #endregion
//        }
        
//        #region Properties
//        public WpfButton UIGenerateScheduleButton
//        {
//            get
//            {
//                if ((this.mUIGenerateScheduleButton == null))
//                {
//                    this.mUIGenerateScheduleButton = new WpfButton(this);
//                    #region Search Criteria
//                    this.mUIGenerateScheduleButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "GenerateButton";
//                    this.mUIGenerateScheduleButton.WindowTitles.Add("Capstone Employee Scheduler - Home");
//                    #endregion
//                }
//                return this.mUIGenerateScheduleButton;
//            }
//        }
//        #endregion
        
//        #region Fields
//        private WpfButton mUIGenerateScheduleButton;
//        #endregion
//    }
//}
